services:
    app.listener.file:
        class: AppBundle\Services\Listener\FileListener
        tags:
        - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\File, event: prePersist }
        - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\File, event: preUpdate }